FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy source code
COPY ./webui/ /app/

# Install dependencies
RUN npm install

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]